---

- name: Create /etc/sysconfig/network-scripts/ifcfg-$INTERFACE
  template:
    src: templates/ifcfg.RedHat.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.name }}"
    mode: 0644
  with_items: "{{ virtual_interface_configs }}"
  register: register_ifcfg

- name: Shutdown changed interfaces if exists
  shell: "if ip link show {{ item.item.name }}>/dev/null; then ifdown {{ item.item.name }}; fi"
  when: "{{ item.changed }}"
  with_items: "{{ register_ifcfg.results }}"

- name: Bring up changed interfaces
  command: "ifup {{ item.item.name }}"
  register: register_ifup
  when: "{{ item.changed }}"
  with_items: "{{ register_ifcfg.results }}"

- assert:
  # make sure stderr does not contain errors
  #
  # XXX there are cases where ifup fails to create an interface but exits with
  # status zero
    that:
      - "{{ item.stderr == '' }}"
    msg: "stderr is not empty: {{ item.stderr }}"
  when: "{{ item.changed }}"
  with_items: "{{ register_ifup.results }}"

- name: Make sure interfaces exist
  command: "ip link show {{ item.name }}"
  changed_when: false
  with_items: "{{ virtual_interface_configs }}"
