---

- name: "Create /etc/network/interfaces.d/{{ iface.name }}"
  template:
    src: interface.Debian.j2
    dest: "/etc/network/interfaces.d/{{ iface.name }}"
    mode: 0644
  register: _if_config_file

- name: "Add source /etc/network/interfaces.d/{{ iface.name }} to /etc/network/interfaces"
  lineinfile:
    dest: /etc/network/interfaces
    line: "source interfaces.d/{{ iface.name }}"

- name: "Shutdown interface {{ iface.name }}"
  shell: "if ip link show {{ iface.name }}>/dev/null; then ifdown {{ iface.name }}; fi"
  when: "{{ _if_config_file.changed }}"

- name: "Bring up interface {{ iface.name }}"
  command: "ifup {{ iface.name }}"
  register: _ifup_command
  when: "{{ _if_config_file.changed }}"
  failed_when: "{{ _ifup_command.stderr != '' }}"

- name: Make sure interface {{ iface.name }} exist
  command: "ip link show {{ iface.name }}"
  changed_when: false
