---
- name: "Create hostname.{{ iface.name }}"
  template:
    src: hostname.if.j2
    dest: "/etc/hostname.{{ iface.name }}"
    mode: 0640
  register: _etc_hostname

- name: "Check if interface {{ iface.name }} exists"
  command: "ifconfig {{ iface.name }}"
  register: _ifconfig_check
  changed_when: false
  ignore_errors: true
  when: "{{ _etc_hostname.changed }}"

- name: "Destroy interface {{ iface.name }} if exists"
  command: "ifconfig {{ iface.name }} destroy"
  when:
    - "{{ _etc_hostname.changed }}"
    - "{{ _ifconfig_check|succeeded }}"

- name: "Apply hostname.{{ iface.name }} change"
  command: "sh /etc/netstart {{ iface.name }}"
  when: "{{ _etc_hostname.changed }}"

- name: "Make sure the {{ iface.name }} do exist"
  command: "ifconfig {{ iface.name }}"
  #
  # XXX it is hard to make sure the configuration for each interface is valid
  # or correct. writing a parser for possible virtual interfaces, anyone?
  when: "{{ _etc_hostname.changed }}"
  changed_when: false
