---

- name: "Create /etc/sysconfig/network-scripts/ifcfg-{{ iface.name }}"
  template:
    src: templates/ifcfg.RedHat.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ iface.name }}"
    mode: 0644
  register: _ifcfg

- name: Shutdown changed interfaces if exists
  shell: "if ip link show {{ iface.name }}>/dev/null; then ifdown {{ iface.name }}; fi"
  when: "{{ _ifcfg.changed }}"

- name: "Bring up interface {{ iface.name }}"
  command: "ifup {{ iface.name }}"
  register: _ifup_command
  when: "{{ _ifcfg.changed }}"
  failed_when: "{{ _ifup_command.stderr != '' }}"

- name: "Make sure interfaces {{ iface.name }} exist"
  command: "ip link show {{ iface.name }}"
  changed_when: false
