---

- name: "Add interface {{ iface.name }} to cloned_interfaces in rc.conf(5)"
  lineinfile:
    dest: /etc/rc.conf
    line: "cloned_interfaces=\"${cloned_interfaces} {{ iface.name }}\""
  register: _cloned_interfaces_line

- name: "Create ifconfig_{{ iface.name }} in rc.conf(5)"
  lineinfile:
    dest: /etc/rc.conf
    line: 'ifconfig_{{ iface.name }}="{{ iface.config | regex_replace("\n", "") }}"'
  register: _ifconfig_line

- name: "Apply the changes to the interface {{ iface.name }}"
  service:
    name: netif
    arguments: "{{ iface.name }}"
    state: restarted
  when: "{{ _cloned_interfaces_line.changed or _ifconfig_line.changed }}"
