---

- name: Create /etc/network/interfaces.d/$INTERFACE
  template:
    src: interface.Debian.j2
    dest: "/etc/network/interfaces.d/{{ item.name }}"
    mode: 0644
  with_items: "{{ virtual_interfaces }}"
  register: register_interfaces_d

- name: Add source /etc/network/interfaces.d/$INTERFACE to /etc/network/interfaces
  lineinfile:
    dest: /etc/network/interfaces
    line: "source interfaces.d/{{ item.name }}"
  with_items: "{{ virtual_interfaces }}"
  register: register_interfaces

- name: Shutdown changed interfaces if exists
  shell: "if ip link show {{ item.item.name }}>/dev/null; then ifdown {{ item.item.name }}; fi"
  when: "{{ item.changed }}"
  with_items: "{{ register_interfaces_d.results }}"

- name: Bring up changed interfaces
  command: "ifup {{ item.item.name }}"
  register: register_ifup
  when: "{{ item.changed }}"
  with_items: "{{ register_interfaces_d.results }}"

- assert:
  # make sure stderr does not contain errors
  #
  # XXX there are cases where ifup fails to create an interface but exits with
  # status zero
    that:
      - "{{ item.stderr == '' }}"
    msg: "stderr is not empty: {{ item.stderr }}"
  when: "{{ item.changed }}"
  with_items: "{{ register_ifup.results }}"

- name: Make sure interfaces exist
  command: "ip link show {{ item.name }}"
  changed_when: false
  with_items: "{{ virtual_interfaces }}"
