---

- name: "Remove hostname.{{ iface.name }}"
  file:
    path: "/etc/hostname.{{ iface.name }}"
    state: absent

- name: "Check if interface {{ iface.name }} exists"
  command: "ifconfig {{ iface.name }}"
  register: _ifconfig_check
  changed_when: false
  ignore_errors: true

- name: "Destroy interface {{ iface.name }}"
  command: "ifconfig {{ iface.name }} destroy"
  when: "{{ _ifconfig_check|succeeded }}"
