---

- name: "Remove /etc/sysconfig/network-scripts/ifcfg-{{ iface.name }}"
  file:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ iface.name }}"
    state: absent

- name: "Check if interface {{ iface.name }} exists"
  command: "ip link show {{ iface.name }}"
  register: _ip_link_show_command
  changed_when: false
  ignore_errors: true

- name: "Destroy interface {{ iface.name }}"
  command: "ip link delete {{ iface.name }}"
  when: "{{ _ip_link_show_command|succeeded }}"

- name: "Make sure interface {{ iface.name }} have been removed"
  shell: "if ip link show {{ iface.name }}; then false; fi"
  changed_when: false
