---

- name: "Check if interface {{ iface.name }} exists"
  command: "ifconfig {{ iface.name }}"
  register: _ifconfig_check
  changed_when: false
  ignore_errors: true

- name: "Destroy interface {{ iface.name }}"
  command: "ifconfig {{ iface.name }} destroy"
  when: "{{ _ifconfig_check|succeeded }}"

- name: Remove cloned_interfaces from /etc/rc.conf
  lineinfile:
    dest: /etc/rc.conf
    regexp: "cloned_interfaces=\"\\${cloned_interfaces} {{ iface.name }}\""
    state: absent

- name: "Remove ifconfig_{{ iface.name }} from /etc/rc.conf"
  lineinfile:
    dest: /etc/rc.conf
    regexp: "^ifconfig_{{ iface.name }}=.*"
    state: absent
