---

- name: "Remove /etc/network/interfaces.d/{{ iface.name }}"
  file:
    path: "/etc/network/interfaces.d/{{ iface.name }}"
    state: absent

- name: "Remove source /etc/network/interfaces.d/{{ iface.name }} in /etc/network/interfaces"
  lineinfile:
    dest: /etc/network/interfaces
    line: "source interfaces.d/{{ iface.name }}"
    state: absent

- name: "Check if interface {{ iface.name }} exists"
  command: "ip link show {{ iface.name }}"
  register: _ip_link_show_command
  changed_when: false
  ignore_errors: true

- name: "Destroy interface {{ iface.name }}"
  command: "ip link delete {{ iface.name }}"
  when: "{{ _ip_link_show_command|succeeded }}"

- name: "Make sure interface {{ iface.name }} have been removed"
  shell: "if ip link show {{ item }}; then false; fi"
  changed_when: false
